In [1]:
import pandas as pd
import numpy as np
import datetime
import os
import torch

In [2]:
if os.path.isfile('./data.pt'):
    data = torch.load('data.pt')
else:
    data = pd.read_excel('220106_자료/KAMIR-V 1Y FU DATA_Cumulative Death_20220106 변수 정리.xlsx', sheet_name='KAMIR-V 1년 F-U DATA', skiprows=[0])

In [3]:
from utils import get_col_dict

col_dict = get_col_dict()

In [4]:
date_cols = [17, 24, 103]
date_data = data.iloc[:, date_cols]

24 - 17
103 - 24

In [5]:
def to_datetime(x):
    """
    Mappting string date to datetime class
    When date is missing or wrong return None

    Args:
        x: string date
    Returns:
        x: datetime
    """
    try:
        x = list(map(int, x.replace('|', ' ').split()))
        return datetime.datetime(*x)
    except:
        return 0

In [6]:
date_data['MI symptom recent time'] = date_data['MI symptom recent time'].apply(to_datetime)
date_data['This hospital Arrival time'] = date_data['This hospital Arrival time'].apply(to_datetime)

C:\Users\kmiii\.conda\envs\py37\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\kmiii\.conda\envs\py37\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [7]:
date_data

,MI symptom recent time,This hospital Arrival time,Balloon time
0,2017-07-12 13:00:00,2017-07-12 13:18:00,2017 | 07 | 12 | 13 | 50
1,2017-03-31 12:07:00,2017-03-31 12:38:00,2017 | 03 | 31 | 13 | 12
2,2017-11-02 11:00:00,2017-11-02 12:59:00,2017 | 11 | 02 | 13 | 44
3,2017-09-24 02:00:00,2017-09-24 06:02:00,2017 | 09 | 24 | 06 | 49
4,2017-04-12 20:00:00,2017-04-13 12:49:00,0017 | 04 | 14 | 08 | 57
...,...,...,...
15623,2018-11-16 08:05:00,2018-11-16 08:43:00,NaN
15624,2019-04-06 08:00:00,2019-04-06 11:00:00,2019 | 04 | 06 | 12 | 00
15625,2020-04-13 19:00:00,2020-04-14 03:37:00,NaN
15626,2020-05-13 22:57:00,2020-05-23 22:57:00,2020 | 05 | 24 | 08 | 50
15627,2016-10-17 07:30:00,2016-10-17 09:15:00,NaN

In [8]:
#date_data.iloc[66,1] - date_data.iloc[66,0]

In [9]:
for i in range(len(date_data)):
    try:
        date_data.iloc[i,1] - date_data.iloc[i,0]
    except:
        print(i)

66
226
230
773
841
1121
1563
1628
1764
2001
2006
2068
2113
2450
2519
2526
2558
2632
2662
2683
2711
3085
3105
3120
3223
3258
3272
3391
3414
3416
3420
3422
3424
3425
3428
3433
3434
3440
3441
3442
3445
3446
3448
3449
3451
3452
3456
3625
3825
4136
4308
4452
4567
4981
4999
5002
5003
5032
5373
5378
5403
5464
5470
5487
5525
5526
5527
5537
5781
5851
5852
6007
6054
6110
6128
6129
6130
6367
6373
6473
6519
6548
6665
6671
6901
7105
7109
7124
7159
7335
7386
7421
7528
7534
7542
7543
7544
7547
7549
7554
7587
7593
7657
7659
7662
7703
7751
7759
7795
7805
7863
7882
7916
7921
7928
7995
8090
8093
8099
8100
8104
8279
8356
8371
8462
8474
8566
8616
8617
8619
8620
8621
8622
8623
8624
9009
9022
9383
9491
9556
9559
9582
9583
9675
9702
9712
9717
9720
9972
10171
10192
10195
10197
10201
10202
10205
10224
10242
10245
10269
10271
10307
10447
10454
10463
10501
10502
10587
10612
10614
10617
10660
10670
10682
10718
10720
10726
10837
10838
10894
10997
10998
11082
11244
11271
11282
11392
11564
11571
11581
11590
11618
11627
11628
11633
11635
11643
11647
11700
11715
11718
11719
11720
11726
11813
12125
12244
12377
12410
12438
12455
12516
12518
12544
12555
12682
12910
12994
13001
13015
13017
13067
13071
13091
13109
13146
13147
13151
13153
13154
13155
13161
13162
13204
13226
13291
13296
13304
13305
13317
13324
13330
13337
13349
13354
13362
13368
13641
13651
13671
13672
13677
13690
13694
13701
13722
13751
13752
13755
13756
13757
13760
13768
13773
13780
13786
13791
13793
13796
13797
13800
13803
13805
13817
13821
14544
14560
14567
14575
14604
15025
15074
15121
15155
15240
15348
15349
15429
15438
15445
15449

In [10]:
#(date_data.iloc[:,1] - date_data.iloc[:,0])