In [1]:
import pandas as pd
import numpy as np
import os
import torch

In [2]:
if os.path.isfile('./data.pt'):
    data = torch.load('data.pt')
else:
    data = pd.read_excel('220106_자료/KAMIR-V 1Y FU DATA_Cumulative Death_20220106 변수 정리.xlsx', sheet_name='KAMIR-V 1년 F-U DATA', skiprows=[0])

In [52]:
outcome_cols = [319, 320, 321, 322, 323, 324, 398, 399, 404, 407, 408, 409, 410, 424, 425, 435, 436, 441, 444, 445, 446, 447, 461, 462]
outcome_data = data.iloc[:, outcome_cols]

405 - 6M_Total death (TD)
406 - Date of TD

442 - 12M_Total death (TD)
443 - Date of TD

In [53]:
outcome_data

,Discharge date,Type of Discharge,Date of death,Cause of death,Cardiac death,non-cardiac death,6 month Follow-up,6M_F/U date,6M_MACE,6M_Cardiac death (CD),...,Rehospitalization d/t HF,1 Year Follow-up,12M_F/U date,12M_MACE,12M_Cardiac death,date of CD,12M_Non-cardiac death,date of NCD,12M_Rehospitalization d/t HF,Rehospitalization d/t HF.1
0,2017 | 07 | 15,Recovery to Home,NaN,NaN,NaN,NaN,1,2018 | 01 | 11,0.0,NaN,...,NaN,1,2018 | 06 | 25,0.0,NaN,NaN,NaN,NaN,0.0,NaN
1,2017 | 04 | 04,Recovery to Home,NaN,NaN,NaN,NaN,1,2017 | 08 | 17,0.0,NaN,...,NaN,1,2018 | 03 | 19,0.0,NaN,NaN,NaN,NaN,0.0,NaN
2,2017 | 11 | 06,Recovery to Home,NaN,NaN,NaN,NaN,1,2018 | 04 | 09,0.0,NaN,...,NaN,1,2018 | 09 | 21,0.0,NaN,NaN,NaN,NaN,0.0,NaN
3,2017 | 09 | 28,Recovery to Home,NaN,NaN,NaN,NaN,1,2018 | 05 | 24,0.0,NaN,...,NaN,1,2018 | 08 | 16,0.0,NaN,NaN,NaN,NaN,0.0,NaN
4,2017 | 04 | 20,Recovery to Home,NaN,NaN,NaN,NaN,1,2017 | 08 | 30,0.0,NaN,...,NaN,1,2018 | 04 | 23,0.0,NaN,NaN,NaN,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15623,2019 | 01 | 11,Recovery to Other Hospital,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15624,2019 | 05 | 20,Recovery to Other Hospital,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15625,2020 | 04 | 16,Recovery to Other Hospital,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15626,2020 | 06 | 02,Recovery to Other Hospital,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15627,2016 | 10 | 21,Recovery to Other Hospital,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,...,NaN,0,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN

In [63]:
outcome_data.iloc[:, 18].fillna(0, inplace=True)
outcome_data.iloc[:, 20].fillna(0, inplace=True)

In [70]:
death_12m = (outcome_data.iloc[:, 18] + outcome_data.iloc[:, 20]).astype(int)

In [75]:
rehospitalization = outcome_data.iloc[:, 22].fillna(0).astype(int)

In [83]:
during_death = data.iloc[:, 321]

In [84]:
during_death[during_death.notna()] = 1

C:\Users\kmiii\.conda\envs\py37\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [87]:
during_death = during_death.fillna(0).astype(int)

In [93]:
print(((during_death == 1) & (rehospitalization == 1)).sum())
print(((during_death == 1) & (death_12m == 1)).sum())

0
510

In [98]:
(death_12m == 1).sum()

906